language: java
jdk:
  - oraclejdk8
sudo: false
install: true
before_script: travis_wait 45 ./mvnw install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true
script: ./mvnw install -q -nsu -Dmaven.test.redirectTestOutputToFile=true -P '!integration'
cache:
  directories:
    - $HOME/.m2/repository/